CREATE TABLE "mi-quiz_question" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mi-quiz_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topic" varchar(256) NOT NULL,
	"type" varchar(50) NOT NULL,
	"question" text NOT NULL,
	"options" jsonb,
	"correctAnswerIndex" integer,
	"correctAnswer" boolean,
	"suggestedAnswer" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"createdById" integer
);
--> statement-breakpoint
CREATE TABLE "mi-quiz_quiz_attempt" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mi-quiz_quiz_attempt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"visitorId" varchar(256),
	"userId" integer,
	"topics" jsonb NOT NULL,
	"totalQuestions" integer NOT NULL,
	"correctAnswers" integer NOT NULL,
	"percentage" integer NOT NULL,
	"answers" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mi-quiz_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mi-quiz_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"password" varchar(256) NOT NULL,
	"role" varchar(50) DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "mi-quiz_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "mi-quiz_question" ADD CONSTRAINT "mi-quiz_question_createdById_mi-quiz_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."mi-quiz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mi-quiz_quiz_attempt" ADD CONSTRAINT "mi-quiz_quiz_attempt_userId_mi-quiz_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."mi-quiz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "question_topic_idx" ON "mi-quiz_question" USING btree ("topic");--> statement-breakpoint
CREATE INDEX "quiz_attempt_user_idx" ON "mi-quiz_quiz_attempt" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "mi-quiz_user" USING btree ("email");