CREATE TABLE "mi-quiz_topic" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mi-quiz_topic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "mi-quiz_topic_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE INDEX "topic_name_idx" ON "mi-quiz_topic" USING btree ("name");